cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "//lib:logging",
        "//lib:point",
        "@com_google_absl//absl/memory",
        "@com_google_absl//absl/strings",
    ],
)
