cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "//lib:point",
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/strings",
    ],
)
