cc_binary(
    name = "part1",
    srcs = ["main.cc"],
    deps = [
        "@com_google_absl//absl/memory",
        "@com_google_absl//absl/strings",
    ],
)

cc_binary(
    name = "part2",
    srcs = ["main2.cc"],
    deps = [
        "@com_google_absl//absl/memory",
        "@com_google_absl//absl/strings",
    ],
)
